numbers=list(map(int, input("Enter numbers separated by space: ").split()))
print("You entered:",numbers)
print("Sum=",sum(numbers))
print("Average=",sum(numbers)/len(numbers))
print("Max value=",max(numbers))
print("Min value=",min(numbers))